/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urepublicana.basesdedatosii;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alex-arch
 */
public class Login_GUI extends javax.swing.JDialog {

    /**
     * Creates new form Usuarios
     */
    private class BotonPulsadoListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            
            accion = e.getActionCommand();
            
            System.out.println("Has pulsado el botón -" + e.getActionCommand() + "-");
        }
    }

    public Login_GUI(java.awt.Frame parent, boolean modal, Connection conection) {
        super(parent, modal);
        initComponents();
        
        con = conection;
        
        setLocationRelativeTo(null);
        
        jButtonCrear.addActionListener(new BotonPulsadoListener());
        jButtonBorrar.addActionListener(new BotonPulsadoListener());
        jButtonVer.addActionListener(new BotonPulsadoListener());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLogin = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jTextLogin = new javax.swing.JTextField();
        jTextDB = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelDB = new javax.swing.JLabel();
        jTextPass = new javax.swing.JPasswordField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(721, 418));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGINS");

        jButtonCrear.setText("Crear login");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar login");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonVer.setText("Ver login");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });

        jTableLogin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Tipo Login", "Fecha de Creación", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTableLogin);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelLogin.setText("Login:");

        jLabelPass.setText("Password:");

        jLabelDB.setText("DB: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabelDB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextDB, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(93, Short.MAX_VALUE)
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelDB, jLabelLogin, jLabelPass});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextDB, jTextLogin, jTextPass});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelLogin)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPass))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDB))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelDB, jLabelLogin, jLabelPass, jTextDB, jTextLogin, jTextPass});

        jTextLogin.setVisible(false);
        jTextDB.setVisible(false);
        jLabelLogin.setVisible(false);
        jLabelPass.setVisible(false);
        jLabelDB.setVisible(false);
        jTextPass.setVisible(false);

        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonVer1.setText("Atrás");
        jButtonVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(jButtonVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jSeparator1)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jButtonVer1))
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jButtonGuardar.setVisible(false);
        jButtonCancelar.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        jTextLogin.setVisible(true);
        jTextPass.setVisible(true);
        jTextDB.setVisible(true);
        jLabelPass.setVisible(true);
        jLabelLogin.setVisible(true);
        jLabelDB.setVisible(true);

        jButtonBorrar.setEnabled(false);
        jButtonVer.setEnabled(false);
        jButtonCrear.setEnabled(false);

        jButtonGuardar.setVisible(true);
        jButtonCancelar.setVisible(true);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       
        System.out.println("accion: " + accion);
        
        if(accion == "Borrar login"){
            System.out.println("Borrado");
            BorrarLogin();
        }
        if (accion == "Crear login"){
            System.out.println("Creado");
            CrearLogin();
        }
        if (accion == "Ver login"){
            System.out.println("Visto");
            
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        jTextLogin.setVisible(false);
        jTextPass.setVisible(true);
        jTextDB.setVisible(false);
        jLabelPass.setVisible(true);
        jLabelLogin.setVisible(false);
        jLabelDB.setVisible(false);

        jButtonBorrar.setEnabled(false);
        jButtonVer.setEnabled(false);
        jButtonCrear.setEnabled(false);

        jButtonGuardar.setVisible(true);
        jButtonCancelar.setVisible(true);

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        jTextLogin.setVisible(false);
        jTextPass.setVisible(false);
        jTextDB.setVisible(false);
        jLabelPass.setVisible(false);
        jLabelLogin.setVisible(false);
        jLabelDB.setVisible(false);

        jButtonBorrar.setEnabled(true);
        jButtonVer.setEnabled(true);
        jButtonCrear.setEnabled(true);

        jButtonGuardar.setVisible(false);
        jButtonCancelar.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVer1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonVer1ActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
        verUsuarios();
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void CrearLogin() {
        try {
            // TODO add your handling code here:
            System.out.println(con.isClosed());
            PreparedStatement add_login = con.prepareStatement("exec sp_addlogin ?, ?, ?");

            add_login.setString(1, jTextLogin.getText());
            add_login.setString(2, jTextPass.getText());
            add_login.setString(3, jTextDB.getText());

            int añadir = add_login.executeUpdate();

            if (añadir < 0) {

                JOptionPane.showMessageDialog(null, "Se ha creado el login correctamente");

                jTextLogin.setVisible(false);
                jTextPass.setVisible(false);
                jTextDB.setVisible(false);
                jLabelPass.setVisible(false);
                jLabelLogin.setVisible(false);
                jLabelDB.setVisible(false);

                jButtonBorrar.setEnabled(true);
                jButtonVer.setEnabled(true);
                jButtonCrear.setEnabled(true);

                jButtonGuardar.setVisible(false);
                jButtonCancelar.setVisible(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BorrarLogin() {
        try {

            PreparedStatement drop_login = con.prepareStatement("exec sp_droplogin ?");

            drop_login.setString(1, jTextLogin.getText());

            boolean borrar = drop_login.execute();

            if (borrar) {

                JOptionPane.showMessageDialog(null, "Se ha borrado el usuario correctamente");

                jTextLogin.setVisible(false);
                jTextPass.setVisible(false);
                jTextDB.setVisible(false);
                jLabelPass.setVisible(false);
                jLabelLogin.setVisible(false);
                jLabelDB.setVisible(false);

                jButtonBorrar.setEnabled(true);
                jButtonVer.setEnabled(true);
                jButtonCrear.setEnabled(true);

                jButtonGuardar.setVisible(false);
                jButtonCancelar.setVisible(false);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void verUsuarios() {
        try {
            String sql = "select sp.name as login,\n"
                    + "       sp.type_desc as login_type,\n"
                    + "       sp.create_date,\n"
                    + "       case when sp.is_disabled = 1 then 'Disabled'\n"
                    + "            else 'Enabled' end as status\n"
                    + "from sys.server_principals sp\n"
                    + "left join sys.sql_logins sl\n"
                    + "          on sp.principal_id = sl.principal_id\n"
                    + "where sp.type not in ('G', 'R')\n"
                    + "order by sp.name;";

            System.out.println(con.isClosed());
            PreparedStatement view_user = con.prepareStatement(sql);
            DefaultTableModel modelo = (DefaultTableModel) jTableLogin.getModel();

            //view_user.setString(1, jTextUsuario.getText());
            ResultSet rs = view_user.executeQuery();

            while (rs.next()) {
                Object[] ob = new Object[4];
                ob[0] = rs.getString(1);
                ob[1] = rs.getString(2);
                ob[2] = rs.getString(3);
                ob[3] = rs.getString(4);
                modelo.addRow(ob);
            }
            rs.close();
            jTextLogin.setVisible(false);
            jTextPass.setVisible(false);
            jTextDB.setVisible(false);
            jLabelPass.setVisible(false);
            jLabelLogin.setVisible(false);
            jLabelDB.setVisible(false);

            jButtonBorrar.setEnabled(true);
            jButtonVer.setEnabled(true);
            jButtonCrear.setEnabled(true);

            jButtonGuardar.setVisible(false);
            jButtonCancelar.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JButton jButtonVer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDB;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableLogin;
    private javax.swing.JTextField jTextDB;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JPasswordField jTextPass;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private String accion;

}
